# TCL File Generated by Component Editor 18.1
# Fri Jun 21 14:20:40 CST 2019
# DO NOT MODIFY


# 
# WS2812_CONTROL "WS2812_CONTROL" v1.0
#  2019.06.21.14:20:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module WS2812_CONTROL
# 
set_module_property DESCRIPTION ""
set_module_property NAME WS2812_CONTROL
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Terasic
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME WS2812_CONTROL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL WS2812_Control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file WS2812_Control.v VERILOG PATH WS2812_IP/WS2812_Control.v TOP_LEVEL_FILE
add_fileset_file ILED_CONTROLLER.v VERILOG PATH WS2812_IP/ILED_CONTROLLER.v
add_fileset_file WS2812.v VERILOG PATH WS2812_IP/WS2812.v
add_fileset_file TWO_PORT_RAM.v VERILOG PATH WS2812_IP/TWO_PORT_RAM.v


# 
# parameters
# 
add_parameter LED_NUM INTEGER 32
set_parameter_property LED_NUM DEFAULT_VALUE 32
set_parameter_property LED_NUM DISPLAY_NAME LED_NUM
set_parameter_property LED_NUM TYPE INTEGER
set_parameter_property LED_NUM UNITS None
set_parameter_property LED_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LED_NUM HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock s_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink s_reset_n reset_n Input 1


# 
# connection point conduit_end_dout
# 
add_interface conduit_end_dout conduit end
set_interface_property conduit_end_dout associatedClock clock
set_interface_property conduit_end_dout associatedReset reset_sink
set_interface_property conduit_end_dout ENABLED true
set_interface_property conduit_end_dout EXPORT_OF ""
set_interface_property conduit_end_dout PORT_NAME_MAP ""
set_interface_property conduit_end_dout CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_dout SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_dout exp_dout export Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave s_write_data writedata Input 32
add_interface_port avalon_slave s_read_data readdata Output 32
add_interface_port avalon_slave s_address address Input 2
add_interface_port avalon_slave s_read_en read Input 1
add_interface_port avalon_slave s_write_en write Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

